### ISSUE TITLE
ValueError: Proxy keys should use proper URL forms rather than plain scheme strings. Instead of "http", use "http://"

### ISSUE THREAD

**Issue by XPKX00** [brkalbyrk/async_holehe#1]
Can you help with the below error : 

─$ sudo python3 async_holehe.py                                                                       1 ⚙
Traceback (most recent call last):
  File "/home/parallels/holehe/holehe/async_holehe/async_holehe.py", line 196, in <module>
    trio.run(main)
  File "/usr/lib/python3/dist-packages/trio/_core/_run.py", line 2010, in run
    raise runner.main_task_outcome.error
  File "/home/parallels/holehe/holehe/async_holehe/async_holehe.py", line 184, in main
    client = httpx.AsyncClient(proxies=proxy_dict)
  File "/usr/lib/python3/dist-packages/httpx/_client.py", line 1411, in __init__
    self._mounts: typing.Dict[URLPattern, typing.Optional[AsyncBaseTransport]] = {
  File "/usr/lib/python3/dist-packages/httpx/_client.py", line 1412, in <dictcomp>
    URLPattern(key): None
  File "/usr/lib/python3/dist-packages/httpx/_utils.py", line 471, in __init__
    raise ValueError(
ValueError: Proxy keys should use proper URL forms rather than plain scheme strings. Instead of "http", use "http://"

**Comment by brkalbyrk** [comment]
The proxy list you have given look to be incorrect, please give it in the correct format and try again.
